apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume-ranganath
  namespace: ranganath
  labels:
    type: local
spec:
  storageClassName: mysql-ranganath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-ranganath"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim-ranganath
  namespace: ranganath
spec:
  storageClassName: mysql-ranganath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi